import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="BiasAnalyzer",
    version="0.0.1",
    description="Package for analyzing biases in scoring models and visualization through a flask webserver",
    long_description="to be filled",
    long_description_content_type="text/markdown",
    url="https://github.com/pypa/sampleproject",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.8',
    # todo: once we have automated tests, make this list minimal
    install_requires=[
        'argon2-cffi==20.1.0',
        'async-generator==1.10',
        'attrs==19.3.0',
        'backcall==0.2.0',
        'bleach==3.2.1',
        'certifi==2020.6.20',
        'cffi==1.14.3',
        'click==7.1.2',
        'cycler==0.10.0',
        'decorator==4.4.2',
        'defusedxml==0.6.0',
        'entrypoints==0.3',
        'fairlearn==0.4.6',
        'Flask==1.1.2',
        'future==0.18.2',
        'hypothesis==5.37.4',
        'ipykernel==5.3.4',
        'ipython==7.18.1',
        'ipython-genutils==0.2.0',
        'ipywidgets==7.5.1',
        'itsdangerous==1.1.0',
        'jedi==0.17.2',
        'Jinja2==2.11.2',
        'joblib==0.17.0',
        'jsonschema==3.2.0',
        'jupyter==1.0.0',
        'jupyter-client==6.1.7',
        'jupyter-console==6.2.0',
        'jupyter-core==4.6.3',
        'jupyterlab-pygments==0.1.2',
        'kiwisolver==1.2.0',
        'MarkupSafe==1.1.1',
        'matplotlib==3.3.2',
        'mistune==0.8.4',
        'more-itertools==8.4.0',
        'nbclient==0.5.1',
        'nbconvert==6.0.7',
        'nbformat==5.0.8',
        'nest-asyncio==1.4.1',
        'notebook==6.1.4',
        'numpy==1.19.2',
        'packaging==20.4',
        'pandas==1.1.3',
        'pandocfilters==1.4.3',
        'parso==0.7.1',
        'pexpect==4.8.0',
        'pickleshare==0.7.5',
        'Pillow==8.0.1',
        'pluggy==0.13.1',
        'prometheus-client==0.8.0',
        'prompt-toolkit==3.0.8',
        'ptyprocess==0.6.0',
        'py==1.9.0',
        'pycparser==2.20',
        'Pygments==2.7.2',
        'pyparsing==2.4.7',
        'pyrsistent==0.17.3',
        'pytest==5.4.3',
        'python-dateutil==2.8.1',
        'pytz==2020.1',
        'pyzmq==19.0.2',
        'qtconsole==4.7.7',
        'QtPy==1.9.0',
        'scikit-learn==0.23.2',
        'scipy==1.5.3',
        'Send2Trash==1.5.0',
        'six==1.15.0',
        'sortedcontainers==2.2.2',
        'terminado==0.9.1',
        'testpath==0.4.4',
        'threadpoolctl==2.1.0',
        'torch==1.6.0',
        'tornado==6.0.4',
        'traitlets==5.0.5',
        'wcwidth==0.2.5',
        'webencodings==0.5.1',
        'Werkzeug==1.0.1',
    ],
)
